= UPD Consulting

We are consultancy and development company, and are big believers of "Applied AI" and of "Cognitive computing".

We build distributed systems behind High-Performance, Cloud, Edge and Fog Computing flavours with "Strong" and "Self organizing" system paradigms in our minds.

And, sure, we support opensource. 

== Services

=== Consulting

As experts in our field, we’re happy to provide consulting services to support our clients. 
We offer consulting for software architecture 
(including enterprise, technology, data, information, integration, logistics and finances), 
as well as for UX and data store and data processing. 
We lead developers and engineers, curate a whole projects and do an auditing tasks.

We're also happy to assist in business transformation and digitisation.

=== Software Development

We design and implement modern and user-friendly applications and software systems, 
cloud-based applications and scalable data-platforms. 
We can also provide specialists to share their expertise, and support our clients’ development teams.

== Repositories

=== Private

The private repositories on GitHub are a convenient way to get sources on-demand by subscription. 
The subscription is also on GitHub so getting a sources or assistance is quick and easy too.

==== Clojure

. com.dkdhub/libmisc-clj -- DKD miscellaneous for Clojure development
. com.dkdhub/qtasks -- DKD Quartz Library for Clojure
